# Generated by Django 5.0.2 on 2024-03-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_remove_wishlistitem_movement_wishlistitem_caliber'),
        ('wishlist', '0005_alter_wishlistitem_year'),
    ]

    operations = [
    ]
