# Generated by Django 5.0.2 on 2024-03-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0008_alter_wishlistitem_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='year',
            field=models.IntegerField(blank=True, choices=[], null=True),
        ),
    ]
