# Generated by Django 5.0.2 on 2024-03-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_brand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
    ]
