# Generated by Django 5.0.2 on 2024-03-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
    ]
