# Generated by Django 5.0.2 on 2024-03-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Club Members'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='editability',
            field=models.BooleanField(default=False),
        ),
    ]
