# Generated by Django 5.0.2 on 2024-03-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_alter_customuser_options_customuser_editability'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_watch_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
