# Generated by Django 5.0.2 on 2024-03-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_customuser_show_watch_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='show_watch_collection',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='show_wishlist',
        ),
        migrations.AddField(
            model_name='customuser',
            name='watch_collection_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('logged_in_users', 'Logged In Users Only'), ('private', 'Private')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wishlist_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('logged_in_users', 'Logged In Users Only'), ('private', 'Private')], default='private', max_length=20),
        ),
    ]
