# Generated by Django 5.0.2 on 2024-03-20 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_remove_customuser_show_watch_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wishlist_visibility',
        ),
    ]
