# Generated by Django 5.0.2 on 2024-03-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_remove_customuser_wishlist_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wishlist_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('logged_in_users', 'Logged In Users Only'), ('private', 'Private')], default='private', max_length=20),
        ),
    ]
