# Generated by Django 5.0.2 on 2024-03-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caliber',
            options={'ordering': ['name']},
        ),
    ]
