# Generated by Django 5.0.2 on 2024-03-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibers', '0002_alter_caliber_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='caliber',
            name='type',
            field=models.CharField(blank=True, choices=[('Automatic', 'Automatic'), ('Mechanical', 'Mechanical'), ('Quartz', 'Quartz'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
