# Generated by Django 5.0.2 on 2024-03-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibers', '0003_caliber_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='caliber',
            name='inhouse',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
