# Generated by Django 5.0.2 on 2024-03-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch_collection', '0003_remove_watch_movement_watch_caliber'),
        ('watch_collection', '0005_alter_watch_year'),
    ]

    operations = [
    ]
