# Generated by Django 5.0.2 on 2024-03-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_collection', '0010_alter_watch_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='on_wishlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watch',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
