# Generated by Django 5.0.2 on 2024-03-22 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_collection', '0011_watch_description_watch_on_wishlist_watch_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
